version: '2'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  php:
    build: ./images/php5 #image: aldump/casexe_php:7.3
    links:
      - mysql
      - redis
    volumes:
      - ./www:/var/www
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    environment:
      SSH_AUTH_SOCK: /ssh-agent
  mysql:
    image: mariadb:latest
    ports:
      - "3348:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/dumps:/docker-entrypoint-initdb.d
      - ./mysql/mysqlconf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casino2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - "6379"